WorkShopUNA/Models/Telefone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using WorkShopUNA.Models.Enum;

namespace WorkShopUNA.Models
{
	[Table("Telefone")]
	public class Telefone
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual int Id { get; set; }

		[Required]
		public virtual string DDD { get; set; }

		[Required]
		public virtual string Numero { get; set; }

		public virtual string Ramal { get; set; }

		[Required]
		public virtual TipoTelefone TipoTelefone { get; set; }

		public int ContatoId { get; set; }

		[ForeignKey("ContatoId")]
		public virtual Contato Contato { get; set; }
	}
}

WorkShopUNA/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkShopUNA.Models;
using WorkShopUNA.Models.Contexto;

namespace WorkShopUNA.Controllers
{
    public class ContatoController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Contato
        public ActionResult Index()
        {
            var contato = db.Contato.Include(c => c.Agenda);
            return View(contato.ToList());
        }

        // GET: Contato/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contato.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // GET: Contato/Create
        public ActionResult Create()
        {
            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome");
            return View();
        }

        // POST: Contato/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Sexo,DataNascimento,AgendaId")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                db.Contato.Add(contato);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome", contato.AgendaId);
            return View(contato);
        }

        // GET: Contato/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contato.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome", contato.AgendaId);
            return View(contato);
        }

        // POST: Contato/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Sexo,DataNascimento,AgendaId")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contato).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome", contato.AgendaId);
            return View(contato);
        }

        // GET: Contato/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contato.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // POST: Contato/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contato contato = db.Contato.Find(id);
            db.Contato.Remove(contato);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

WorkShopUNA/Controllers/TelefoneController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkShopUNA.Models;
using WorkShopUNA.Models.Contexto;

namespace WorkShopUNA.Controllers
{
    public class TelefoneController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Telefone
        public ActionResult Index(int Id)
        {
			ViewBag.ContatoId = Id;
            var telefone = db.Telefone.Include(t => t.Contato).Where(x=>x.Contato.Id == Id);
            return View(telefone.ToList());
        }

        // GET: Telefone/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telefone telefone = db.Telefone.Find(id);
            if (telefone == null)
            {
                return HttpNotFound();
            }
            return View(telefone);
        }

        // GET: Telefone/Create
        public ActionResult Create(int ContatoId)
        {
			ViewBag.ContatoId = ContatoId;
            return View();
        }

        // POST: Telefone/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DDD,Numero,Ramal,TipoTelefone,ContatoId")] Telefone telefone)
        {
            if (ModelState.IsValid)
            {
                db.Telefone.Add(telefone);
                db.SaveChanges();
				return RedirectToAction("Index", new { Id = telefone.ContatoId });
            }

            ViewBag.ContatoId = telefone.ContatoId;
            return View(telefone);
        }

        // GET: Telefone/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telefone telefone = db.Telefone.Find(id);
            if (telefone == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContatoId = telefone.ContatoId;
            return View(telefone);
        }

        // POST: Telefone/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DDD,Numero,Ramal,TipoTelefone,ContatoId")] Telefone telefone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(telefone).State = EntityState.Modified;
                db.SaveChanges();
				return RedirectToAction("Index", new { Id = telefone.ContatoId });
            }
            ViewBag.ContatoId = telefone.ContatoId;
            return View(telefone);
        }

        // GET: Telefone/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telefone telefone = db.Telefone.Find(id);
            if (telefone == null)
            {
                return HttpNotFound();
            }
            return View(telefone);
        }

        // POST: Telefone/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Telefone telefone = db.Telefone.Find(id);
			var ContatoId = telefone.Contato.Id;
            db.Telefone.Remove(telefone);
            db.SaveChanges();
			return RedirectToAction("Index", new { Id = ContatoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkShopUNA/Views/Telefone/Create.cshtml
@model WorkShopUNA.Models.Telefone

@{
    ViewBag.Title = "Cadastrar Telefone";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Telefone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("ContatoId",(int)ViewBag.ContatoId)
        <div class="form-group">
            @Html.LabelFor(model => model.DDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DDD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ramal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ramal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ramal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoTelefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoTelefone, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a listagem de contatos", "Index", new{ ContatoId = ViewBag.ContatoId  }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkShopUNA/Views/Telefone/Delete.cshtml
@model WorkShopUNA.Models.Telefone

@{
    ViewBag.Title = "Deletar telefone";
}

<h2>@ViewBag.Title </h2>

<h3>Tem certeza que deseja deletar o telefone do @Model.Contato.Nome ?</h3>
<div>
    <h4>Telefone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DDD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DDD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ramal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ramal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoTelefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoTelefone)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-danger" /> 
            @Html.ActionLink("Voltar a listagem de contatos", "Index", new { Id = Model.Contato.Id }, new { @class = "btn btn-primary" })
        </div>
    }
</div>

WorkShopUNA/Views/Telefone/Details.cshtml
@model WorkShopUNA.Models.Telefone

@{
    ViewBag.Title = "Detalhar telefone";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Telefone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contato.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DDD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DDD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ramal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ramal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoTelefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoTelefone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Voltar a listagem de telefones", "Index", new { Id = Model.Contato.Id }, new { @class = "btn btn-primary" })
</p>

WorkShopUNA/Views/Telefone/Edit.cshtml
@model WorkShopUNA.Models.Telefone

@{
    ViewBag.Title = "Editar Telefone";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Telefone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(x=>x.Contato.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.DDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DDD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ramal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ramal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ramal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoTelefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoTelefone, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a listagem de contatos", "Index", new { Id = Model.Contato.Id }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkShopUNA/Views/Telefone/Index.cshtml
@model IEnumerable<WorkShopUNA.Models.Telefone>

@{
    ViewBag.Title = "Listagem de Telefones";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Cadastrar telefone", "Create", new { ContatoId = ViewBag.ContatoId }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Contato.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DDD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ramal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoTelefone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Contato.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DDD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ramal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoTelefone)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-warning" })
                @Html.ActionLink("Detalhar", "Details", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id }, new { @class = "btn btn-sm btn-danger" })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Voltar para listagem de Contatos", "Index", "Contato",null, new { @class = "btn btn-primary" })
</div>