WorkShopUNA/Models/Contato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using WorkShopUNA.Models.Enum;

namespace WorkShopUNA.Models
{
	[Table("Contato")]
	public class Contato
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual int Id { get; set; }

		[Required]
		public virtual string Nome { get; set; }

		[Required]
		public virtual Sexo Sexo { get; set; }

		[Required]
		[Display(Name = "Data de Nascimento")]
		[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
		[DataType(DataType.DateTime)]
		public virtual DateTime DataNascimento { get; set; }

		[NotMapped]
		public int Idade
		{
			get
			{
				if(DataNascimento == DateTime.MinValue)
					return 0;
				else
				{
					DateTime hoje = DateTime.Today;
					int idade = hoje.Year - DataNascimento.Year;
					if (DataNascimento > hoje.AddYears(-idade)) idade--;
					return idade;
				}
			}
		}

		public int AgendaId { get; set; }

		[ForeignKey("AgendaId")]
		public virtual Agenda Agenda { get; set; }

		public virtual IList<Endereco> Enderecos { get; set; }

		public virtual IList<Telefone> Telefones { get; set; }

		public Contato()
		{
			Enderecos = new List<Endereco>();
			Telefones = new List<Telefone>();
		}
	}
}

WorkShopUNA/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkShopUNA.Models;
using WorkShopUNA.Models.Contexto;

namespace WorkShopUNA.Controllers
{
    public class ContatoController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Contato
        public ActionResult Index()
        {
            var contato = db.Contato.Include(c => c.Agenda);
            return View(contato.ToList());
        }

        // GET: Contato/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contato.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // GET: Contato/Create
        public ActionResult Create()
        {
            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome");
            return View();
        }

        // POST: Contato/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Sexo,DataNascimento,AgendaId")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                db.Contato.Add(contato);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome", contato.AgendaId);
            return View(contato);
        }

        // GET: Contato/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contato.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome", contato.AgendaId);
            return View(contato);
        }

        // POST: Contato/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Sexo,DataNascimento,AgendaId")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contato).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AgendaId = new SelectList(db.Agenda, "Id", "Nome", contato.AgendaId);
            return View(contato);
        }

        // GET: Contato/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contato contato = db.Contato.Find(id);
            if (contato == null)
            {
                return HttpNotFound();
            }
            return View(contato);
        }

        // POST: Contato/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contato contato = db.Contato.Find(id);
            db.Contato.Remove(contato);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

WorkShopUNA/Controllers/EnderecoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkShopUNA.Models;
using WorkShopUNA.Models.Contexto;

namespace WorkShopUNA.Controllers
{
    public class EnderecoController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Endereco
		public ActionResult Index(int Id)
        {
			ViewBag.ContatoId = Id;
            var endereco = db.Endereco.Include(e => e.Contato).Where(x=>x.Contato.Id == Id);
            return View(endereco.ToList());
        }

        // GET: Endereco/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // GET: Endereco/Create
		public ActionResult Create(int ContatoId)
        {
			ViewBag.ContatoId = ContatoId;
            return View();
        }

        // POST: Endereco/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CEP,Rua,Bairro,Cidade,Estado,Complemento,ContatoId")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                db.Endereco.Add(endereco);
                db.SaveChanges();
				return RedirectToAction("Index", new { Id = endereco.ContatoId });
            }

			ViewBag.ContatoId = endereco.ContatoId;
            return View(endereco);
        }

        // GET: Endereco/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
			ViewBag.ContatoId = endereco.ContatoId;
            return View(endereco);
        }

        // POST: Endereco/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CEP,Rua,Bairro,Cidade,Estado,Complemento,ContatoId")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                db.Entry(endereco).State = EntityState.Modified;
                db.SaveChanges();
				return RedirectToAction("Index", new { Id = endereco.ContatoId });
            }
			ViewBag.ContatoId = endereco.ContatoId;
            return View(endereco);
        }

        // GET: Endereco/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // POST: Endereco/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Endereco endereco = db.Endereco.Find(id);
			int ContatoId = endereco.ContatoId;
            db.Endereco.Remove(endereco);
            db.SaveChanges();
			return RedirectToAction("Index", new { Id = ContatoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkShopUNA/Controllers/TelefoneController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkShopUNA.Models;
using WorkShopUNA.Models.Contexto;

namespace WorkShopUNA.Controllers
{
    public class TelefoneController : Controller
    {
        private AppContext db = new AppContext();

        // GET: Telefone
        public ActionResult Index(int Id)
        {
			ViewBag.ContatoId = Id;
            var telefone = db.Telefone.Include(t => t.Contato).Where(x=>x.Contato.Id == Id);
            return View(telefone.ToList());
        }

        // GET: Telefone/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telefone telefone = db.Telefone.Find(id);
            if (telefone == null)
            {
                return HttpNotFound();
            }
            return View(telefone);
        }

        // GET: Telefone/Create
        public ActionResult Create(int ContatoId)
        {
			ViewBag.ContatoId = ContatoId;
            return View();
        }

        // POST: Telefone/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DDD,Numero,Ramal,TipoTelefone,ContatoId")] Telefone telefone)
        {
            if (ModelState.IsValid)
            {
                db.Telefone.Add(telefone);
                db.SaveChanges();
				return RedirectToAction("Index", new { Id = telefone.ContatoId });
            }

            ViewBag.ContatoId = telefone.ContatoId;
            return View(telefone);
        }

        // GET: Telefone/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telefone telefone = db.Telefone.Find(id);
            if (telefone == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContatoId = telefone.ContatoId;
            return View(telefone);
        }

        // POST: Telefone/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DDD,Numero,Ramal,TipoTelefone,ContatoId")] Telefone telefone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(telefone).State = EntityState.Modified;
                db.SaveChanges();
				return RedirectToAction("Index", new { Id = telefone.ContatoId });
            }
            ViewBag.ContatoId = telefone.ContatoId;
            return View(telefone);
        }

        // GET: Telefone/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Telefone telefone = db.Telefone.Find(id);
            if (telefone == null)
            {
                return HttpNotFound();
            }
            return View(telefone);
        }

        // POST: Telefone/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Telefone telefone = db.Telefone.Find(id);
			var ContatoId = telefone.Contato.Id;
            db.Telefone.Remove(telefone);
            db.SaveChanges();
			return RedirectToAction("Index", new { Id = ContatoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkShopUNA/Views/Contato/Create.cshtml
@model WorkShopUNA.Models.Contato

@{
    ViewBag.Title = "Cadastrar novo contato";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Contato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sexo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgendaId, "Agenda", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AgendaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgendaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a listagem de contatos", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkShopUNA/Views/Contato/Delete.cshtml
@model WorkShopUNA.Models.Contato

@{
    ViewBag.Title = "Deletar contato";
}

<h2>@ViewBag.Title </h2>

<h3>Tem certeza que deseja deletar o @Model.Nome ?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agenda.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-danger" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class="btn btn-primary"})
        </div>
    }
</div>

WorkShopUNA/Views/Contato/Details.cshtml
@model WorkShopUNA.Models.Contato

@{
    ViewBag.Title = "Detalhar";
}

<h2>Contato</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agenda.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agenda.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Voltar a listagem de contatos", "Index", null, new { @class = "btn btn-primary" })
</p>

WorkShopUNA/Views/Contato/Edit.cshtml
@model WorkShopUNA.Models.Contato

@{
    ViewBag.Title = "Editar contato";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Contato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sexo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgendaId, "Agenda", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AgendaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgendaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a listagem de contatos", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkShopUNA/Views/Contato/Index.cshtml
@model IEnumerable<WorkShopUNA.Models.Contato>

@{
    ViewBag.Title = "Contatos";
}

<h2>Lista de Contatos</h2>

<p>
    @Html.ActionLink("Cadastrar novo contato", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Agenda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Agenda.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-warning" })
                @Html.ActionLink("Detalhar", "Details", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id }, new { @class = "btn btn-sm btn-danger" })
                <a href="@Url.Action("Index", "Telefone", new { id = item.Id })" class="btn btn-sm btn-default">Telefones <span class="badge">@item.Telefones.Count</span></a>
                <a href="@Url.Action("Index", "Endereco", new { id = item.Id })" class="btn btn-sm btn-default">Endereços <span class="badge">@item.Enderecos.Count</span></a>
            </td>
        </tr>
    }

</table>